spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ganjudb?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  profiles:
    active: local
    group:
      local: common, secret
---

spring:
  output:
    ansi:
      enabled: always
  config:
    activate:
      on-profile: common

  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        format_sql: true

    defer-datasource-initialization: true
server:
  port: 8081