spring:
  profiles:
    active: local
    group:
      local: common, secret
---

spring:
  output:
    ansi:
      enabled: always
  config:
    activate:
      on-profile: common
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ganjudb?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234

  sql:
    init:
      mode: always

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        format_sql: true

    defer-datasource-initialization: true
server:
  port: 8081
